### ISSUE TITLE
Solve Gimbal Lock

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/DarkPlaces#209] opened 2024-10-06 16:16 UTC
Here I set avelocity to "100 0 100", it should rotate diagonally (right?)

I assume that this is caused by Gimbal lock (related to how there are multiple ways to get the same angle with pitch yaw roll).

![gimbal](https://github.com/user-attachments/assets/2cffdf51-1171-4c3d-8c9f-dbf3537e9caa)

I imagine fteqw has this solved it has MOVETYPE_6DOF (six degrees of freedom) -- a movetype like a flight simulator.

**Comment by hemebond** [comment] 2024-12-17 11:13
Isn't this just because `avelocity` just sets the angular velocity around each world axis? To get rotation around arbitrary axis we'd need to use `angle`/`angles` or something to first adjust the "facing".

**Comment by Baker7** [comment] 2024-12-18 09:30
I think that isn't correct because avelocity changes the angles.

If I recall I did numerous experiments using every trick in the book and I think I would have tried that too, but I'm not fresh on this at the moment.

**Comment by Baker7** [comment] 2024-12-18 10:56
Thinking about this more ... I do believe you are correct.

**Comment by hemebond** [comment] 2024-12-18 11:00
When I wanted rotation around arbitrary axis, for brush-based sentry turrets, I had to add special handling in QuakeC with matrix stuff taken from func_vehicle. https://gitlab.com/hemebond/quake-raiders/-/blob/64523bf790b5ee7cc3955a3d55e148f206e6e40a/qc/sv_func_datacore.qc#L137

**Comment by Baker7** [comment] 2024-12-18 16:27
Thank you for the link.

I think I know a "hideous" way to pull this off with setattachment.  When possible, I want to push matrix calculations into the engine instead of QuakeC.  The beauty of the attachment system is that each attachment inherits the matrix of what it is being attached to

**Comment by hemebond** [comment] 2024-12-19 03:14
I didn't know about the attachment feature when creating my turret, but it probably would have made it _so much easier_.

I'm going to go ahead and close this ticket as it seems to be working as intended.

**Closed by hemebond** 2024-12-19 03:14 UTC
